# Generated by Django 3.1.2 on 2020-10-09 13:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emprestimo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('banco', models.TextField(max_length=150)),
                ('cliente', models.TextField(max_length=100)),
                ('data_da_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('valor_nominal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('parcelas', models.IntegerField()),
                ('taxa_de_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('endereco_de_ip', models.GenericIPAddressField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_da_solicitacao',),
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagamento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_do_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='emprestimos.emprestimo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_do_pagamento',),
            },
        ),
    ]
